### ISSUE TITLE
HACS Install Issue

### ISSUE THREAD

**Issue by titelies** [crserran/home-alarm#3] opened 2020-06-04 19:53 UTC
Should the directory name be home_alarm or home-alarm. The info on this page: https://crserran.github.io/home-alarm/installation/ shows home_alarm but the install from HACS creates a directory named home-alarm.  HACS only adds the 1 file: home_alarm.py while the manual install shows 3 other directories: ha_alert, ha_core, ha_utils.
Not sure how to complete the setup, the identification page is also incomplete.
Any info is greatly appreciated, really looking forward to getting this working.

**Comment by crserran** [comment] 2020-06-04 20:48
Hi @titelies thank you for your issue. It’s true, the documentation is wrong, I didn’t realize that HACS do the conversion of “_” to “-“ of the parent folder, then the folder should be named “home-alarm”. I will fix it soon🙂.

Anyway I would like to tell you that the 3 directories that you said is from dev branch, so these changes are not reflected on any release yet. I recommend you to change to master branch and install it manually but changing the name “home_alarm” to “home-alarm”.

I hope I helped you.

**Comment by titelies** [comment] 2020-06-04 21:12
Ok @crserran I have switched to the master branch, renamed the directory to home-alarm in HA and now the only file in the directory is the home_alarm.py.
Sorry for my confusion, still new to all this, where do I put this info that is specific to my setup:
home_alarm:
  module: home_alarm
  class: HomeAlarm
  sensors:
    - binary_sensor.foyer_door_contact
    - binary_sensor.garage_backdoor_contact
    - binary_sensor.garage_door_tilt_sensor_contact
    - binary_sensor.garage_backdoor_contact
    - binary_sensor.kitchen_motion_sensor_motion
    - binary_sensor.upstairs_hallway_motion_sensor_motion
  safe_mode: input_boolean.safe_mode
  activation_delay: 10
  media_player: media_player.kitchen_tap
  sound: amzn_sfx_scifi_alarm_03
  loop_delay: 5
  stop_delay: 240
  notifiers:
    - notify.notifier
  alert_title: "ALARM ALERT!"
  alert_msg: "Alarm has been fired"

**Comment by crserran** [comment] 2020-06-04 21:21
First of all, I assume that you have installed AppDeamon integration from Supervisor. This action creates an appdeamon folder inside your config directory in HA. Once you have this you should see an apps folder and apps.yaml file inside apps folder (/config/appdeamon/apps/apps.yaml). 

The setup yaml that you send me has to be included inside apps.yaml file.

If you do this you will have home-alarm working properly🙂

**Comment by titelies** [comment] 2020-06-04 21:29
I do have AppDeamon installed but there is no apps.yaml in the config/appdeamon/apps directory.
![Screenshot](https://user-images.githubusercontent.com/16294530/83811853-8ed04b80-a688-11ea-8caf-1d5d33b690bb.png)
Should I try a reinstall? Thanks again for your continued support.

**Comment by titelies** [comment] 2020-06-04 22:25
So, I reinstalled AppDaemon and now I have the correct directories and files, including apps.yaml,
I added my Home Alarm info to apps.yaml and when I check the logs it seems to load properly except an Error for Safe Mode Not Found: 
WARNING home_alarm: home_alarm: Entity input_boolean.safe_mode not found in namespace default

**Comment by xaviml** [comment] 2020-06-05 06:07
Hi @titelies, do you have the input_boolen.safe_mode created from HA (either UI or configurarion.yaml)?

You will need this input_boolean before starting Home Alarm with AppDaemon.

**Comment by crserran** [comment] 2020-06-05 06:35
Hi @titelies, what @xaviml is saying is correct, you need to configure input_boolean.safe_mode first. I recommend to follow this link https://www.home-assistant.io/integrations/input_boolean/

This input boolean is used to active the protected mode of the house, you can call it as you want. If input boolean is true, then it means you want to active alarm when some sensor detects something (i.e. a window open). If input boolean is false, then no alarm will be activated even you open windows or doors.

**Comment by titelies** [comment] 2020-06-05 13:38
Thanks guys, I did find that input_boolean page last night and created it using the Configuration > Helpers. I was up til really late working on this. I got @crserran example sound (amzn_sfx_scifi_alarm_04) to play, for some reason the one I choose amzn_sfx_scifi_alarm_03 wasn't working, even changed the loop_delay to 5. Also, wasn't able to get the sound to play on multiple Echo devices, hoping it's not cause I have many of the older generation Echo Taps even though I have them setup as audio notification devices throughout my house for many SmartThings SmartApp tasks and it works great.

Couldn't really test too much cuz I had people sleeping in the house, will keep at it today. No more error messages though in AppDaemon but I did have to delete my older AppDaemon directory and do a fresh install.

**Comment by crserran** [comment] 2020-06-06 16:49
Hi @titelies, I have realized that the sound you are trying to reproduce is not working from Developer Tools in HA also. I don't know exactly why but there are some sounds that don't work probably because Amazon problems... 

Regarding of multiple Alexa devices, it is not implemented yet in Release 1.0.0 but this functionality will come for the next release. I hope I will be publishing a new version soon :)

**Comment by titelies** [comment] 2020-06-07 17:34
@crserran Yeah, its odd that the audio I preferred isn't working. Currently, using the one you provided in the example. I am however able to broadcast to multiple Echo devices (even the older Tap models) using the following:
  media_player:
    - media_player.fire_tv_cube
    - media_player.kitchen_tap
    - media_player.basement_tap
    - media_player.master_echo_dot_with_clock
Thanks for all the help and look forward to updates. A nice option would be to return the Echo volume to a default 5 or 6 instead of max.
Thanks again!

**Comment by crserran** [comment] 2020-06-08 08:12
@titelies Great to hear that you were able to execute multiple at the same time. I am currently preparing the new release and the volume will be an input from the apps.yaml :)

Thank you!

**Comment by crserran** [comment] 2020-06-10 18:10
I close the issue due to the new Release v2.0.0. Many thanks :)

**Closed as completed by crserran** 2020-06-10 18:10 UTC
Labels: documentation, question
